manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    # My fork with some additions like urob's mouse keys.
    - name: jasonish
      url-base: git@github.com:jasonish
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
    - name: zmk
      remote: jasonish
      revision: picks/v1
      import: app/west.yml
  self:
    path: config
